### ISSUE TITLE
ES6 syntax

### ISSUE THREAD

**Issue by AntoLepejian** [Devzstudio/MERN-Snippets#1]
Is there a way for me to edit the code snippets to change to ES6 syntax? or are there any plans to update them?

**Comment by PJijin** [comment]
If you can place the Pull Request I can update that. And Yes I have the plan to update the syntax and add more snippets.

**Comment by AntoLepejian** [comment]
I found the snippets file in the .vscode folder and am updating some of them now. I am new to MERN tho so some of the snippets I haven't seen before. will make a PR once finished

**Comment by PJijin** [comment]
Cool 😃
